# Módulo 07, Tarefa 01

Vamos começar a mexer na nossa base de projeto? Já fizemos um exercício de montar a variável resposta, já pudemos perceber que essa atividade pode não ser trivial. Vamos agora trabalhar a base para que fique propícia ao *scikitlearn* para trabalharmos.

Lembrando, a base se chama demo01.csv, e originalmente está publicada [aqui](https://www.kaggle.com/rikdifos/credit-card-approval-prediction).

#### 1) Carregue a base e avalie:

- As variáveis
- Tipos de dados de cada variável
- Quantidade de missings
- Distribuição da variável resposta (mau)

In [2]:
import pandas as pd

df = pd.read_csv('demo01.csv')
print(f'TIPOS DE DADOS DE CADA VARIÁVEL\n{df.dtypes}')
print(f'\nQUANTIDADE DE MISSINGS\n{df.isna().sum()}')
print(f"\nDISTRIBUIÇÃO DA VARIÁVEL MAU\n{df['mau'].value_counts()}")

TIPOS DE DADOS DE CADA VARIÁVEL
sexo                      object
posse_de_veiculo          object
posse_de_imovel           object
qtd_filhos                 int64
tipo_renda                object
educacao                  object
estado_civil              object
tipo_residencia           object
idade                    float64
tempo_emprego            float64
possui_celular             int64
possui_fone_comercial      int64
possui_fone                int64
possui_email               int64
qt_pessoas_residencia    float64
mau                         bool
dtype: object

QUANTIDADE DE MISSINGS
sexo                     0
posse_de_veiculo         0
posse_de_imovel          0
qtd_filhos               0
tipo_renda               0
educacao                 0
estado_civil             0
tipo_residencia          0
idade                    0
tempo_emprego            0
possui_celular           0
possui_fone_comercial    0
possui_fone              0
possui_email             0
qt_pessoas_residencia    0
mau                      0
dtype: int64

DISTRIBUIÇÃO DA VARIÁVEL MAU
False    16260
True       390
Name: mau, dtype: int64

#### 2) Vamos montar um metadados

1. Crie um dataframe com os nomes de cada variável e o tipo de dados de cada variável.
2. Adicione uma coluna nesse *dataframe* chamada "qtd_categorias" e coloque nela o número de categorias correspondente de cada variável.
    Dica:
        1. inicie uma lista vazia
        2. faça um for ao longo dos nomes das variáveis,
        3. conte o número de categorias dessa variável
        4. acumule essa informação de 3. na lista que você criou em 1.
        5. No final, essa lista pode ser atribuída à nossa variável.
3. Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}.

In [3]:
#criacao de dataframe com nomes e tipos de variavel
df_dtypes = df.dtypes.to_frame()
df_variaveis = df_dtypes.reset_index()
df_variaveis.columns = ['variavel', 'tipo']

#calcula o numero de categorias de cada variavel
ncategorias = []
for cat in df.columns:
  ncategorias.append(df[cat].nunique())
df_variaveis['ncategorias'] = ncategorias
print(f'\nCATEGORIAS\n{df_variaveis}')

CATEGORIAS
                 variavel     tipo  ncategorias
0                    sexo   object            2
1        posse_de_veiculo   object            2
2         posse_de_imovel   object            2
3              qtd_filhos    int64            8
4              tipo_renda   object            5
5                educacao   object            5
6            estado_civil   object            5
7         tipo_residencia   object            6
8                   idade  float64         5298
9           tempo_emprego  float64         3005
10         possui_celular    int64            1
11  possui_fone_comercial    int64            2
12            possui_fone    int64            2
13           possui_email    int64            2
14  qt_pessoas_residencia  float64            9
15                    mau     bool            2

#### 3) Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}. Crie um *dataframe* apenas com as variáveis apropriadas para entrada no scikitlearn - elimine as variáveis tipo *str*, mantendo apenas suas versões *dummy*.

In [4]:

#remove variaveis nao qualitativas
drop_columns=df_variaveis.loc[df_variaveis['tipo'] == 'float64', 'variavel']
df1 = df.drop(columns=drop_columns)
df2 = df1.drop('qtd_filhos', axis=1, errors='ignore')
print(f'\nDF DTYPES\n{df2.dtypes}')

df2['mau']=df2['mau'].astype('int')
df2['sexo']=df2['sexo'].map({'M':0, 'F':1})
df2['posse_de_veiculo']=df2['posse_de_veiculo'].map({'N':0, 'Y':1})
df2['posse_de_imovel']=df2['posse_de_imovel'].map({'N':0, 'Y':1})
df3=pd.get_dummies(df2, columns=['tipo_renda', 'educacao', 'estado_civil', 'tipo_residencia'], drop_first=True)

df3.head()

DF DTYPES
sexo                     object
posse_de_veiculo         object
posse_de_imovel          object
tipo_renda               object
educacao                 object
estado_civil             object
tipo_residencia          object
possui_celular            int64
possui_fone_comercial     int64
possui_fone               int64
possui_email              int64
mau                        bool
dtype: object

,sexo,posse_de_veiculo,posse_de_imovel,possui_celular,possui_fone_comercial,possui_fone,possui_email,mau,tipo_renda_Pensioner,tipo_renda_State servant,...,educacao_Secondary / secondary special,estado_civil_Married,estado_civil_Separated,estado_civil_Single / not married,estado_civil_Widow,tipo_residencia_House / apartment,tipo_residencia_Municipal apartment,tipo_residencia_Office apartment,tipo_residencia_Rented apartment,tipo_residencia_With parents
0,0,1,1,1,0,0,0,0,0,0,...,1,1,0,0,0,1,0,0,0,0
1,1,0,1,1,0,1,1,0,0,0,...,1,0,0,1,0,1,0,0,0,0
2,1,0,1,1,0,1,1,0,0,0,...,1,0,0,1,0,1,0,0,0,0
3,0,1,1,1,1,1,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
4,1,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0

#### 4) Qual variável é mais poderosa?

Considere as variáveis ```possui_email``` e ```posse_de_veiculo```. Faça uma tabela cruzada entre elas e responda qual delas te parece mais poderosa para prever a probabilidade de ```mau = 1```?

In [13]:
pd.crosstab(df3.possui_email, df3.mau)

mau               0    1
possui_email
0             14810  360
1              1450   30

In [14]:
pd.crosstab(df3.posse_de_veiculo, df3.mau)

mau                  0    1
posse_de_veiculo
0                 9931  247
1                 6329  143

#### 5) Salve a base, pois ela será utilizada no final deste módulo.

verificando as tabelas acima, notamos que a variável **possui_email** é mais indicativa para o mau pagador. Não sei o termo certo, mas os valores dessa variável para os maus pagadores são mais distintos. Então, o valor 0 para a variável possui_email aponta mais certamente para um mau pagador.

Podem me fornecer a explicação com os termos corretos, por favor?

In [6]:
df3.to_csv('/demo01-tratado.csv')